name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: create .env file
        run: |
         cat << EOF > .env
         ${{ vars.DEPLOY_ENV_FILE }}
         EOF
      - name: install project dependencies
        run: npm install
      - name: build project
        run: npm run build
      - name: deploy project
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ vars.DEPLOY_SSH_HOST }}
          USER: ${{ vars.DEPLOY_SSH_USERNAME }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SOURCE: "./"
          TARGET: ${{ vars.DEPLOY_DEPLOY_PATH }}
          ARGS: "-zrlp --delete --exclude=/.git/ --exclude=/.github/"
      - name: start project
        uses: appleboy/ssh-action@v1.1.0
        env:
          DEPLOY_PATH: ${{ vars.DEPLOY_DEPLOY_PATH }}
        with:
          host: ${{ vars.DEPLOY_SSH_HOST }}
          username: ${{ vars.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            source ~/.profile
            cd "$DEPLOY_PATH"
            npx prisma generate
            set -x
            pm2 start ecosystem.config.js
            pm2 save
            set +x
